name: lynx-blackwell
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=6.1.1=hecf7045_5
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openh264=2.6.0=he621ea3_0
  - openjdk=11.0.1=h516909a_1016
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aac-datasets==0.7.0
      - accelerate==1.10.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.0.1
      - av==15.1.0
      - awscli==1.44.29
      - boto3==1.42.39
      - botocore==1.42.39
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - contourpy==1.3.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - decorator==5.2.1
      - deepspeed==0.18.3
      - dill==0.3.8
      - docutils==0.19
      - ego4d==1.7.3
      - einops==0.8.1
      - executing==2.2.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - h5py==3.15.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - huggingface-hub==0.35.3
      - idna==3.11
      - inflate64==1.0.3
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.1.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mmengine==0.10.7
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - ninja==1.13.0
      - numba==0.62.1
      - numpy==2.2.6
      - nvidia-cublas==13.1.0.3
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-runtime==13.0.96
      - nvidia-cudnn-cu13==9.15.1.9
      - nvidia-cufft==12.0.0.61
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu13==2.28.9
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - parameterized==0.9.0
      - parso==0.8.5
      - peft==0.13.2
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py7zr==1.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.2
      - pybcj==1.0.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.11
      - pycparser==2.23
      - pycryptodomex==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyppmd==1.2.0
      - python-dateutil==2.9.0.post0
      - pythonwrench==0.4.1
      - pytorchvideo==0.1.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzstd==0.18.0
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.7.2
      - s3transfer==0.16.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.1.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - timm==1.0.20
      - tokenizers==0.20.3
      - torch==2.11.0.dev20260114+cu130
      - torchaudio==2.11.0.dev20260114+cu130
      - torchvision==0.25.0.dev20260114+cu130
      - torchwrench==0.7.5
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.45.1
      - triton==3.6.0+git9844da95
      - types-regex==2025.9.18.20250921
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.3
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.22.0
      - yt-dlp==2025.9.26
prefix: /home/mmai/anaconda3/envs/unit
